Exposing the CONNECT response details of chained tunnels via a new event
apify/proxy-chain pull request #116
Opened 2021-02-22 21:27 UTC by starrify

This is considered useful when some proxy providers may include useful information (e.g. for debugging) in the CONNECT response headers.

Implements #30.

This PR is based on the earlier commit in #31 (thanks @Benraay!) with these additional changes:
- Resolved conflicts between the earlier commit and the current `master` branch.
- Added a new test case for this very feature
- Slightly adjusted the callback interface in `listenConnectAnonymizedProxy`
- Renamed the event name (`onTrgRequestConnect` -> `tunnelConnectResponded`) for this may be accessed by users directly (via `server.on`).

2021-02-22 21:46 UTC, Benraay commented
Good news !
Never got the time to add tests thanks for going on !

2021-02-22 22:33 UTC, jancurn requested changes
Looks great, many thanks! I've just a small comment. Also, would be great if you could add a short description to README about this event and function.

2021-02-22 22:33 UTC, jancurn commented on src/anonymize_proxy.js
> +        tunnelConnectRespondedCallback(false);
Would be better to return `null`, to avoid mixing of types (object vs boolean). And you probably need to return from the function.

2021-02-22 22:33 UTC, jancurn commented on src/anonymize_proxy.js
> + * @param tunnelConnectRespondedCallback
Please could you describe the callback params here?

2021-02-22 23:47 UTC, starrify commented
Hi @jancurn , thanks for the rapid response and the review opinions. I've had this PR updated accordingly by adding two new commits.

2021-02-23 13:10 UTC, jancurn approved these changes
Awesome, many thanks for a nice PR.

2021-02-24 10:35 UTC, mnmkng approved these changes
Nice, thanks!

2021-02-24 10:35 UTC, merged

2021-11-02 15:48 UTC, thomas510111 commented
I think it would be a good idea to also pass the proxyChainId. Created a PR.
https://github.com/apify/proxy-chain/pull/173