Add support for custom dns lookup
apify/proxy-chain pull request #175
Opened 2021-11-02 18:05 UTC by thomas510111

Default dns.lookup() is running on libuv threadpool and on high load or issues with the dns server it can cause increased latency in getting the initial connection.
https://github.com/nodejs/node/issues/8436

In my opinion the best way to "patch" this is allow users to use their own dns lookup function.

2021-11-02 18:11 UTC, thomas510111 commented
By the way, I havent worked with typescript and couldnt figure out how to properly declare type of dnsLookup.

2021-12-30 01:35 UTC, szmarczak requested changes

2021-12-30 01:35 UTC, szmarczak commented on src/chain.ts
> +    lookup?: any;
Please type this properly.

2021-12-30 01:36 UTC, szmarczak commented on src/chain.ts
> +    lookup?: any;
I think it should be possible to `dns['lookup']` or `typeof dns['lookup']`

2022-05-02 08:54 UTC, merged

2025-03-21 11:20 UTC, freeway7 commented
How to set custom DNS server?