Use key/value object in place of Array for requests headers
apify/proxy-chain pull request #528
Opened 2024-01-10 21:21 UTC by Elyahou

I came across an issue where the `anonymizeProxy` helper  function was not working correctly, and upstream proxy was returning 407, even if the username/password was correctly set in the proxy url.

I found out that the upstream proxy was not receiving the credential header correctly. `http` and `https` request should contain header according to [the API](https://nodejs.org/docs/latest-v14.x/api/http.html#http_http_request_options_callback).

With the proposed changes, the `anonymizeProxy` works correctly, and I no longer have errors

2024-01-10 21:32 UTC, jancurn approved these changes
Thanks for the PR, the changes look reasonable, I'm just surprised it used to work before...

2024-01-10 21:33 UTC, jancurn requested changes
Just the tests are failing now...

2024-01-10 22:13 UTC, Elyahou commented
yes, so it seems that original implementation with array is to allow repeating headers, and my change break this.

2024-01-10 22:40 UTC, Elyahou commented
It seems `http` support sending an array of value to support repeating headers, so I changed the `forward` function accordingly

2024-01-14 12:24 UTC, closed without merging

2024-01-14 14:31 UTC, jancurn commented
So it worked fine with the array too, instead of object? The reason why we use array of raw headers is to preserve all even duplicate headers to make the proxy transparent.