fix: correctly validate protocols in anonymize_proxy
apify/proxy-chain pull request #545
Opened 2024-08-16 07:39 UTC by jirimoravcik

This PR fixes validation of URL protocol for `anonymize_proxy.ts`

2024-08-16 09:14 UTC, drobnikj requested changes
Let's add test for socks protocol, otherwise fine 👍

2024-08-16 09:14 UTC, drobnikj commented on test/anonymize_proxy.js
> -        assert.throws(() => { anonymizeProxy('socks://whatever.com'); }, Error);
Let's add test that some of socks protocol work.

2024-08-16 09:14 UTC, drobnikj commented on src/anonymize_proxy.ts
> +        throw new Error(`Invalid "proxyUrl" provided: URL must have one of the following protocols: "http", ${SOCKS_PROTOCOLS.map((p) => `"${p.replace(':', '')}"`).join(', ')} (was "${parsedProxyUrl}
```suggestion
        throw new Error(`Invalid "proxyUrl" provided: URL must have one of the following protocols: "http", ${SOCKS_PROTOCOLS.map((p) => `"${p.replace(':', '')}"`).join(', ')} (was "${parsedProxyUrl}").`);
```

2024-08-16 10:08 UTC, jancurn approved these changes

2024-08-19 08:50 UTC, drobnikj approved these changes

2024-08-19 08:56 UTC, merged