https support for proxy relay
apify/proxy-chain pull request #564
Opened 2024-11-20 18:44 UTC by arenevier

Fix for issue #563

2024-11-20 21:05 UTC, jancurn approved these changes
Thanks for the improvement, it looks like a reasonable change. Any chance you could also update the tests?

2024-11-20 21:18 UTC, arenevier commented
Would be happy to modify the tests. But I'm not sure what to modify. Also, running the tests hang on my laptop, after the following output:

```

% npm test

> proxy-chain@2.5.5 test
> nyc cross-env NODE_OPTIONS=--insecure-http-parser mocha --bail



(node:232095) Warning: Using insecure HTTP parsing
(Use `node --trace-warnings ...` to show where the warning was created)
  ✔ supports localAddress
  ✔ supports custom CONNECT server handler
  ✔ supports pre-response CONNECT payload
  utils.anonymizeProxy
    ✔ throws for invalid args
    ✔ throws for unsupported https: protocol
    ✔ throws for invalid ports
    ✔ throws for invalid URLs
    ✔ keeps already anonymous proxies (both with callbacks and promises)
    1) anonymizes authenticated upstream proxy (both with callbacks and promises)


  8 passing (63ms)
  1 failing

  1) utils.anonymizeProxy
       anonymizes authenticated upstream proxy (both with callbacks and promises):
     AssertionError: expected 'socket hang up' to include 'ECONNREFUSED'
      at /home/arno/src/proxy-chain/test/anonymize_proxy.js:236:48
      at processTicksAndRejections (node:internal/process/task_queues:95:5)

```

2024-11-21 19:21 UTC, arenevier commented
I added a test. I was not able to connect to a https server in the test. But in the test, I can check that proxyServer does not consider the relay url as invalid. The code snippet will fail without the PR, and pass with it.

2024-12-02 15:08 UTC, jirimoravcik requested changes

2024-12-02 15:08 UTC, jirimoravcik commented on test/server.js
> +    const target = https.createServer((_req, _res) => {
```suggestion
    const target = https.createServer(() => {
```

2024-12-02 15:08 UTC, jirimoravcik commented on test/server.js
> +    proxy.on('requestFailed', (_err) => {
```suggestion
    proxy.on('requestFailed', () => {
```

2024-12-02 15:08 UTC, jirimoravcik commented on test/server.js
> +            }
```suggestion
            };
```

2024-12-02 15:08 UTC, jirimoravcik commented on test/server.js
> +        }
```suggestion
        },
```

2024-12-02 15:08 UTC, jirimoravcik commented on test/server.js
> +    })
```suggestion
    });
```

2024-12-02 15:08 UTC, jirimoravcik commented on test/server.js
> +})
```suggestion
});
```

2024-12-02 15:08 UTC, jirimoravcik commented on test/server.js
> +    const proxy = new ProxyChain.Server({
please rename this to `proxyServer`

2024-12-02 18:57 UTC, jirimoravcik approved these changes

2024-12-02 18:57 UTC, merged